sudo: false
language: python
env:
- DEBUG=1
python: "3.4"
install:
  - pip install -U pip
  - pip install flake8
script:
  - flake8 django_managerie
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
