sudo: false
language: python
env:
- DEBUG=1
python:
  - "3.6"
  - "3.8"
install:
  - pip install -U pip
script:
  - pip install -e .
  - python setup.py sdist bdist_wheel
  - pip install -r requirements-dev.txt
  - flake8 django_managerie
  - tox -- --cov .
