name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - python-version: '3.8'
          - python-version: '3.10'
          - python-version: '3.12'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python-version }}'
          cache: pip
          cache-dependency-path: pyproject.toml
      - run: pip install --upgrade tox tox-gh
      - run: tox
  Lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: pyproject.toml
      - uses: pre-commit/action@v3.0.1
