name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python-version: '3.6'
          - python-version: '3.10'
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run: pip install -U pip
      - run: pip install -U tox tox-gh-actions
      - run: tox
  Lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: pyproject.toml
      - uses: pre-commit/action@v3.0.0
