name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python-version: '3.6'
          - python-version: '3.10'
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run: pip install -U pip
      - run: pip install -U tox tox-gh-actions
      - run: tox
  Lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions/checkout@v2
      - run: pip install -U pip
      - run: pip install -r requirements-dev.txt django-stubs
      - run: flake8 django_managerie
      - run: mypy --show-error-codes django_managerie
