name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.10"
          - python-version: "3.11"
          - python-version: "3.12"
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "${{ matrix.python-version }}"
          cache-dependency-glob: pyproject.toml
      - run: uvx --with=tox-gh --with=tox-uv tox
  Lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: akx/pre-commit-uv-action@v0.1.0
